### ISSUE TITLE
As a user, there are business rules around certificate fields so I do not incorrectly enter them.

### ISSUE THREAD

**Issue by porta-antiporta** [USKPA-dev/uskpa#45]
- [x] Date of expiry is 60 days after date of issue
- [x] Order of dates is the following
    - Assigned
    - Prepared
    - Shipped
    - Delivered
    - i.e. `Delivered` can't be earlier than `Shipped` etc
- [x] HTS Code is one of: 7102.10, 7102.21 and 7102.31
- [x] When preparing a certificate, all fields visible on the certificate are mandatory fields.
- [x] Validation on amount paid should be $20 x # of certificates sold

**Comment by Jkrzy** [comment]
Implementing these rules in #74.

We also need to implement logic to validate the requested certificates from the Certificate Registration page.

Users should receive an error message if any of the requested Certificates already exist, via sequential or list input.

**Comment by porta-antiporta** [comment]
@Jkrzy to clarify, the added logic is to provide an error message to the user when say a duplicate certificate is to be assigned.

IIRC, there already is logic to safeguard from issuing duplicate certificates, there's just no notification/reason as to why it fails.

**Comment by Jkrzy** [comment]
Resolving last piece in #92.

I don't believe this is a concern since `Certificate` records are mapped 1-1 to physical paper forms but to note here:

 On the registration page,  we're not explicitly making available gaps in the sequence of Certificates issued.  The `next available` certificate is always set to the highest `Certificate.number` currently in the database,  +1. 

If someone uses the `list` method of certificate registration to create `US1` and `US3` the next available certificate is reported as `US4`. 

`US2` would be available and may be created w/ a later registration or via the admin but that may not be immediately apparent from the registration page alone.
